---
title: "Survival analysis -- combining features, POP, OAK, IMP130"
author: "Xiao Li"
date: "11/23/2022"
output: 
  html_document:
    toc: yes
    toc_depth: 2
    number_sections: TRUE
    code_folding: hide
pkgdown:
  as_is: true
vignette: >
  %\VignetteIndexEntry{Risk factors for critical illness}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, dpi = 100, fig.width = 8, fig.height = 8)
```


# load dependencies
```{r, warning=F}
rm(list = ls())

library('uwot')
library('dplyr')
select <- dplyr::select
library('ggplot2')
library('survival')
library("survminer")
library('openxlsx')
library('caret')
library('tidyverse')
library('rpart')
library('rpart.plot')
library('randomForest')
library('e1071')
library('openxlsx')
library('pROC')

custom_theme <- function() {
  theme_survminer() %+replace%
    theme(
      plot.title=element_text(hjust=0.5)
    )
}


set.seed(12345)

```


# training using POPLAR dataset
```{r}
load("~/gRED_DP_OAK/HK_POPLAR_alltiles_100_cutoff=0.25.RData")
comb_res = comb_res[, -which(colnames(comb_res) == "ID")[1]]

POP_manual = read.csv('POPLAR_with_BCOR.csv')[, c("ID", "immunophenotype")]

Xiao_dat = merge(comb_res, POP_manual, by = "ID")

Xiao_dat = Xiao_dat[!is.na(Xiao_dat$immunophenotype),]


Jeff_POP = read.xlsx('20220211_poplar_bins.xlsx', sheet = 2)
Jeff_POP$ID = paste0(Jeff_POP$Sample.ID, '_', Jeff_POP$StarLiMS.ID, '_ckpos_tiles.csv')
Jeff_POP = Jeff_POP[, c(35, 16:24, 26:34, 12)]

combine_POP = Jeff_POP %>% inner_join(Xiao_dat %>% select(-"immunophenotype"), by = "ID") %>% select(-"ID")
combine_POP = combine_POP[, 19:ncol(combine_POP)]

#5 folds repeat 10 times
control <- trainControl(method = 'repeatedcv', 
                        number = 5, 
                        repeats = 10)

#Number randomely variable selected is mtry
mtry <- round(sqrt(ncol(combine_POP)-1))
tunegrid <- expand.grid(.mtry = mtry)

rf_training <- train(Manual_Immunophenotype ~ ., 
                     data = combine_POP, 
                     method = 'rf', 
                     preProcess = NULL,
                     ntree = 200,
                     tuneGrid = tunegrid, 
                     trControl = control)

save(rf_training, file = "pop_trn_model_pip3.RData")

# rfImp = varImp(rf_training, scale = F)
# plot(rfImp, top = 20) 


```


# harmonize different data source for OAK, we include the subject with multiple sample but concordant IP calls
```{r, warning = F}
load("~/gRED_DP_OAK/HK_OAK_alltiles_100_cutoff=0.25.RData")
Xiao_OAK = comb_res[, -which(colnames(comb_res) == "ID")[1]]

Jeff_OAK = readxl::read_excel('COLLATE_OAK_HK_final_20220606153656.xlsx', sheet = 1, col_types = c(rep("text", 10), rep("numeric", 27))) %>% mutate(Final.call = `Final consensus manual phenotype`)

Jeff_OAK$ID = paste0(Jeff_OAK$Sample.ID, '_', Jeff_OAK$StarLiMS.ID, '_ckpos_tiles.csv')

Hauke_dat = read.csv('Patient-MetaData_GO28915_OAK_v070_2112120_for-Darya - PatientDataTable_GO28915_OAK_new_210828.csv')

combine_OAK = Xiao_OAK %>% inner_join(Jeff_OAK[, c(4,2,3, 18:39)], by = "ID") %>%
                inner_join(Hauke_dat %>% select(USUBJID, ACTARM, OS_MONTHS, OS_CENSOR, PFS_MONTHS, PFS_CENSOR), by = "USUBJID")  %>% 
                mutate(Final.call = factor(Final.call, levels = c("Inflamed", "Excluded", "Desert")))


fea = names(rf_training$trainingData)[-which(names(rf_training$trainingData) == ".outcome")]

names(combine_OAK)[55:74] = gsub(" ", ".", names(combine_OAK)[55:74])

combine_OAK = combine_OAK[complete.cases(combine_OAK), ]
```


# prediction on OAK (combing arms)
```{r}
pred <- predict(rf_training, 
                combine_OAK[, fea], 
                type = "prob")

xtab = table(factor(c("Desert", "Excluded", "Inflamed")[apply(pred, 1, which.max)], levels = c("Inflamed", "Excluded", "Desert"))
, combine_OAK$Final.call)

print(paste0("Classification accuracy is ", sum(diag(xtab))/sum(xtab)))

vcd::Kappa(xtab)
xtab
```



# OS Survival analysis (OAK)
```{r}
COLOR <- c("#ED7D31", "#4472C4", "#A5A5A5")

A_dat = combine_OAK %>% filter(ACTARM == "atezo")
D_dat = combine_OAK %>% filter(ACTARM == "doce") 

pred <- predict(rf_training, 
                A_dat[, fea], 
                type = "prob")

A_dat$spat = factor(c("Desert", "Excluded", "Inflamed")[apply(pred, 1, which.max)], levels = c("Inflamed", "Excluded", "Desert"))

pred <- predict(rf_training, 
                D_dat[, fea], 
                type = "prob")

D_dat$spat = factor(c("Desert", "Excluded", "Inflamed")[apply(pred, 1, which.max)], levels = c("Inflamed", "Excluded", "Desert"))

A_dat = A_dat %>% select(spat, Final.call, cutoff = `Cutoff prediction`, SVM = `SVM prediction`, OS_MONTHS, OS_CENSOR, PFS_MONTHS, PFS_CENSOR)

A_dat$cutoff = factor(A_dat$cutoff, levels = c("Inflamed", "Excluded", "Desert"))
A_dat$SVM = factor(A_dat$SVM, levels = c("Inflamed", "Excluded", "Desert"))


D_dat = D_dat %>% select(spat, Final.call, cutoff = `Cutoff prediction`, SVM = `SVM prediction`, OS_MONTHS, OS_CENSOR, PFS_MONTHS, PFS_CENSOR)

D_dat$cutoff = factor(D_dat$cutoff, levels = c("Inflamed", "Excluded", "Desert"))
D_dat$SVM = factor(D_dat$SVM, levels = c("Inflamed", "Excluded", "Desert"))

```


```{r}
#######################################################################################################
########################        OS for cut-off, LATIS and manual methods       ########################
#######################################################################################################

## Atezo arm

fit_spat <- survfit(Surv(OS_MONTHS, OS_CENSOR) ~ spat, data = A_dat)
fit_manual <- survfit(Surv(OS_MONTHS, OS_CENSOR) ~ Final.call, data = A_dat)
fit_cutoff <- survfit(Surv(OS_MONTHS, OS_CENSOR) ~ cutoff, data = A_dat)
fit_SVM <- survfit(Surv(OS_MONTHS, OS_CENSOR) ~ SVM, data = A_dat)


p_spat_A_OS = ggsurvplot(fit_spat, data = A_dat, palette = COLOR, size = 1.5, 
                font.main = c(16, "bold"), legend.title = "Immunophenotyping",
                legend.labs = c("Inflamed", "Excluded", "Desert"),
                conf.int = F,          # Add confidence interval
                pval = FALSE,              # Add p-value
                risk.table = TRUE,  title = "OS for Atezo by spat method", ggtheme=custom_theme(),
                surv.median.line = "hv")

p_val = survdiff(Surv(OS_MONTHS, OS_CENSOR) ~ spat, data = A_dat)
p_val = round(pchisq(q = p_val$chisq, df = 2, lower.tail = F), 5)

med_time = surv_median(fit_spat)[,2]

p_spat_A_OS$plot <- p_spat_A_OS$plot +
  annotate("text", size = 5, x = 28, y = 0.8, label = paste0("p=", p_val), cex=4, col="black", vjust=0, hjust = 1.1, fontface=1) + 
  annotate("text", size = 5, x = med_time[1], y = 0.6, label = round(med_time[1], 1), cex=4, col="black", vjust=0, hjust = 0, fontface=1) + 
  annotate("text", size = 5, x = med_time[2], y = 0.6, label = round(med_time[2], 1), cex=4, col="black", vjust=0, hjust = -0.2, fontface=1) + 
  annotate("text", size = 5, x = med_time[3], y = 0.6, label = round(med_time[3], 1), cex=4, col="black", vjust=0, hjust = 1.5, fontface=1)

print(p_spat_A_OS)




p_manual_A_OS = ggsurvplot(fit_manual, data = A_dat, palette = COLOR, size = 1.5, 
                font.main = c(16, "bold"), legend.title = "Immunophenotyping", 
                legend.labs = c("Inflamed", "Excluded", "Desert"), 
                conf.int = F,          # Add confidence interval
                pval = FALSE,              # Add p-value
                risk.table = TRUE,  title = "OS for Atezo by manual method", ggtheme=custom_theme(),
                surv.median.line = "hv")

p_val = survdiff(Surv(OS_MONTHS, OS_CENSOR) ~ Final.call, data = A_dat)
p_val = round(pchisq(q = p_val$chisq, df = 2, lower.tail = F), 5)

med_time = surv_median(fit_manual)[,2]

p_manual_A_OS$plot <- p_manual_A_OS$plot +
  annotate("text", size = 5, x = 28, y = 0.8, label = paste0("p=", p_val), cex=4, col="black", vjust=0, hjust = 1.1, fontface=1) + 
  annotate("text", size = 5, x = med_time[1], y = 0.6, label = round(med_time[1], 1), cex=4, col="black", vjust=0, hjust = 0.2, fontface=1) + 
  annotate("text", size = 5, x = med_time[2], y = 0.6, label = round(med_time[2], 1), cex=4, col="black", vjust=0, hjust = 1, fontface=1) + 
  annotate("text", size = 5, x = med_time[3], y = 0.6, label = round(med_time[3], 1), cex=4, col="black", vjust=0, hjust = -0.6, fontface=1)

print(p_manual_A_OS)


p_cutoff_A_OS = ggsurvplot(fit_cutoff, data = A_dat, palette = COLOR, size = 1.5, 
                         font.main = c(16, "bold"), legend.title = "Immunophenotyping",
                         legend.labs = c("Inflamed", "Excluded", "Desert"),
                         conf.int = F,          # Add confidence interval
                         pval = FALSE,              # Add p-value
                         risk.table = TRUE,  title = "OS for Atezo by cutoff method", ggtheme=custom_theme(),
                         surv.median.line = "hv")

p_val = survdiff(Surv(OS_MONTHS, OS_CENSOR) ~ cutoff, data = A_dat)
p_val = round(pchisq(q = p_val$chisq, df = 2, lower.tail = F), 5)

med_time = surv_median(fit_cutoff)[,2]

p_cutoff_A_OS$plot <- p_cutoff_A_OS$plot +
  annotate("text", size = 5, x = 28, y = 0.8, label = paste0("p=", p_val), cex=4, col="black", vjust=0, hjust = 1.1, fontface=1) + 
  annotate("text", size = 5, x = med_time[1], y = 0.6, label = round(med_time[1], 1), cex=4, col="black", vjust=0, hjust = 1.5, fontface=1) + 
  annotate("text", size = 5, x = med_time[2], y = 0.6, label = round(med_time[2], 1), cex=4, col="black", vjust=0, hjust = 0, fontface=1) + 
  annotate("text", size = 5, x = med_time[3], y = 0.6, label = round(med_time[3], 1), cex=4, col="black", vjust=0, hjust = -1, fontface=1)

print(p_cutoff_A_OS)





p_SVM_A_OS = ggsurvplot(fit_SVM, data = A_dat, palette = COLOR, size = 1.5, 
                         font.main = c(16, "bold"), legend.title = "Immunophenotyping",
                         legend.labs = c("Inflamed", "Excluded", "Desert"),
                         conf.int = F,          # Add confidence interval
                         pval = FALSE,              # Add p-value
                         risk.table = TRUE,  title = "OS for Atezo by SVM method", ggtheme=custom_theme(),
                         surv.median.line = "hv")

p_val = survdiff(Surv(OS_MONTHS, OS_CENSOR) ~ SVM, data = A_dat)
p_val = round(pchisq(q = p_val$chisq, df = 2, lower.tail = F), 5)

med_time = surv_median(fit_spat)[,2]

p_SVM_A_OS$plot <- p_SVM_A_OS$plot +
  annotate("text", size = 5, x = 28, y = 0.8, label = paste0("p=", p_val), cex=4, col="black", vjust=0, hjust = 1.1, fontface=1) + 
  annotate("text", size = 5, x = med_time[1], y = 0.6, label = round(med_time[1], 1), cex=4, col="black", vjust=0, hjust = 0, fontface=1) + 
  annotate("text", size = 5, x = med_time[2], y = 0.6, label = round(med_time[2], 1), cex=4, col="black", vjust=0, hjust = -0.2, fontface=1) + 
  annotate("text", size = 5, x = med_time[3], y = 0.6, label = round(med_time[3], 1), cex=4, col="black", vjust=0, hjust = 1.5, fontface=1)

print(p_SVM_A_OS)






## Doce arm

fit_spat <- survfit(Surv(OS_MONTHS, OS_CENSOR) ~ spat, data = D_dat)
fit_manual <- survfit(Surv(OS_MONTHS, OS_CENSOR) ~ Final.call, data = D_dat)
fit_cutoff <- survfit(Surv(OS_MONTHS, OS_CENSOR) ~ cutoff, data = D_dat)
fit_SVM <- survfit(Surv(OS_MONTHS, OS_CENSOR) ~ SVM, data = D_dat)


p_spat_D_OS = ggsurvplot(fit_spat, data = D_dat, palette = COLOR, size = 1.5, 
                             font.main = c(16, "bold"), legend.title = "Immunophenotyping",
                             legend.labs = c("Inflamed", "Excluded", "Desert"),
                             conf.int = F,          # Add confidence interval
                             pval = FALSE,              # Add p-value
                             risk.table = TRUE,  title = "OS for Doce by spat method", ggtheme=custom_theme(),
                             surv.median.line = "hv")

p_val = survdiff(Surv(OS_MONTHS, OS_CENSOR) ~ spat, data = D_dat)
p_val = round(pchisq(q = p_val$chisq, df = 2, lower.tail = F), 5)

med_time = surv_median(fit_spat)[,2]

p_spat_D_OS$plot <- p_spat_D_OS$plot +
  annotate("text", size = 5, x = 28, y = 0.8, label = paste0("p=", p_val), cex=4, col="black", vjust=0, hjust = 1.1, fontface=1) + 
  annotate("text", size = 5, x = med_time[1], y = 0.6, label = round(med_time[1], 1), cex=4, col="black", vjust=0, hjust = 0, fontface=1) + 
  annotate("text", size = 5, x = med_time[2], y = 0.6, label = round(med_time[2], 1), cex=4, col="black", vjust=0, hjust = -1.5, fontface=1) + 
  annotate("text", size = 5, x = med_time[3], y = 0.6, label = round(med_time[3], 1), cex=4, col="black", vjust=0, hjust = 2, fontface=1)

print(p_spat_D_OS)




p_manual_D_OS = ggsurvplot(fit_manual, data = D_dat, palette = COLOR, size = 1.5, 
                           font.main = c(16, "bold"), legend.title = "Immunophenotyping", 
                           legend.labs = c("Inflamed", "Excluded", "Desert"), 
                           conf.int = F,          # Add confidence interval
                           pval = FALSE,              # Add p-value
                           risk.table = TRUE,  title = "OS for Doce by manual method", ggtheme=custom_theme(),
                           surv.median.line = "hv")

p_val = survdiff(Surv(OS_MONTHS, OS_CENSOR) ~ Final.call, data = D_dat)
p_val = round(pchisq(q = p_val$chisq, df = 2, lower.tail = F), 5)

med_time = surv_median(fit_manual)[,2]

p_manual_D_OS$plot <- p_manual_D_OS$plot +
  annotate("text", size = 5, x = 28, y = 0.8, label = paste0("p=", p_val), cex=4, col="black", vjust=0, hjust = 1.1, fontface=1) + 
  annotate("text", size = 5, x = med_time[1], y = 0.6, label = round(med_time[1], 1), cex=4, col="black", vjust=0, hjust = 0, fontface=1) + 
  annotate("text", size = 5, x = med_time[2], y = 0.6, label = round(med_time[2], 1), cex=4, col="black", vjust=0, hjust = -1.5, fontface=1) + 
  annotate("text", size = 5, x = med_time[3], y = 0.6, label = round(med_time[3], 1), cex=4, col="black", vjust=0, hjust = 1.5, fontface=1)

print(p_manual_D_OS)



p_cutoff_D_OS = ggsurvplot(fit_cutoff, data = D_dat, palette = COLOR, size = 1.5, 
                         font.main = c(16, "bold"), legend.title = "Immunophenotyping",
                         legend.labs = c("Inflamed", "Excluded", "Desert"),
                         conf.int = F,          # Add confidence interval
                         pval = FALSE,              # Add p-value
                         risk.table = TRUE,  title = "OS for Doce by cutoff method", ggtheme=custom_theme(),
                         surv.median.line = "hv")

p_val = survdiff(Surv(OS_MONTHS, OS_CENSOR) ~ cutoff, data = D_dat)
p_val = round(pchisq(q = p_val$chisq, df = 2, lower.tail = F), 5)

med_time = surv_median(fit_cutoff)[,2]

p_cutoff_D_OS$plot <- p_cutoff_D_OS$plot +
  annotate("text", size = 5, x = 28, y = 0.8, label = paste0("p=", p_val), cex=4, col="black", vjust=0, hjust = 1.1, fontface=1) + 
  annotate("text", size = 5, x = med_time[1], y = 0.6, label = round(med_time[1], 1), cex=4, col="black", vjust=0, hjust = 0, fontface=1) + 
  annotate("text", size = 5, x = med_time[2], y = 0.6, label = round(med_time[2], 1), cex=4, col="black", vjust=0, hjust = -1.5, fontface=1) + 
  annotate("text", size = 5, x = med_time[3], y = 0.6, label = round(med_time[3], 1), cex=4, col="black", vjust=0, hjust = 2, fontface=1)

print(p_cutoff_D_OS)




p_SVM_D_OS = ggsurvplot(fit_SVM, data = D_dat, palette = COLOR, size = 1.5, 
                         font.main = c(16, "bold"), legend.title = "Immunophenotyping",
                         legend.labs = c("Inflamed", "Excluded", "Desert"),
                         conf.int = F,          # Add confidence interval
                         pval = FALSE,              # Add p-value
                         risk.table = TRUE,  title = "OS for Doce by SVM method", ggtheme=custom_theme(),
                         surv.median.line = "hv")

p_val = survdiff(Surv(OS_MONTHS, OS_CENSOR) ~ SVM, data = D_dat)
p_val = round(pchisq(q = p_val$chisq, df = 2, lower.tail = F), 5)

med_time = surv_median(fit_SVM)[,2]

p_SVM_D_OS$plot <- p_SVM_D_OS$plot +
  annotate("text", size = 5, x = 28, y = 0.8, label = paste0("p=", p_val), cex=4, col="black", vjust=0, hjust = 1.1, fontface=1) + 
  annotate("text", size = 5, x = med_time[1], y = 0.6, label = round(med_time[1], 1), cex=4, col="black", vjust=0, hjust = 0, fontface=1) + 
  annotate("text", size = 5, x = med_time[2], y = 0.6, label = round(med_time[2], 1), cex=4, col="black", vjust=0, hjust = -1.5, fontface=1) + 
  annotate("text", size = 5, x = med_time[3], y = 0.6, label = round(med_time[3], 1), cex=4, col="black", vjust=0, hjust = 2, fontface=1)

print(p_SVM_D_OS)



```



# PFS Survival analysis (OAK)
```{r}

#######################################################################################################
########################        PFS for cut-off, LATIS and manual methods       ########################
#######################################################################################################

## Atezo arm

fit_spat <- survfit(Surv(PFS_MONTHS, PFS_CENSOR) ~ spat, data = A_dat)
fit_manual <- survfit(Surv(PFS_MONTHS, PFS_CENSOR) ~ Final.call, data = A_dat)
fit_cutoff <- survfit(Surv(PFS_MONTHS, PFS_CENSOR) ~ cutoff, data = A_dat)
fit_SVM <- survfit(Surv(PFS_MONTHS, PFS_CENSOR) ~ SVM, data = A_dat)


p_spat_A_PFS = ggsurvplot(fit_spat, data = A_dat, palette = COLOR, size = 1.5, 
                             font.main = c(16, "bold"), legend.title = "Immunophenotyping",
                             legend.labs = c("Inflamed", "Excluded", "Desert"),
                             conf.int = F,          # Add confidence interval
                             pval = FALSE,              # Add p-value
                             risk.table = TRUE,  title = "PFS for Atezo by spat method", ggtheme=custom_theme(),
                             surv.median.line = "hv")

p_val = survdiff(Surv(PFS_MONTHS, PFS_CENSOR) ~ spat, data = A_dat)
p_val = round(pchisq(q = p_val$chisq, df = 2, lower.tail = F), 5)

med_time = surv_median(fit_spat)[,2]

p_spat_A_PFS$plot <- p_spat_A_PFS$plot +
  annotate("text", size = 5, x = 28, y = 0.8, label = paste0("p=", p_val), cex=4, col="black", vjust=0, hjust = 1.1, fontface=1) + 
  annotate("text", size = 5, x = med_time[1], y = 0.6, label = round(med_time[1], 1), cex=4, col="black", vjust=0, hjust = -2, fontface=1) + 
  annotate("text", size = 5, x = med_time[2], y = 0.6, label = round(med_time[2], 1), cex=4, col="black", vjust=0, hjust = 0, fontface=1) + 
  annotate("text", size = 5, x = med_time[3], y = 0.6, label = round(med_time[3], 1), cex=4, col="black", vjust=0, hjust = 2, fontface=1)

print(p_spat_A_PFS)




p_manual_A_PFS = ggsurvplot(fit_manual, data = A_dat, palette = COLOR, size = 1.5, 
                           font.main = c(16, "bold"), legend.title = "Immunophenotyping", 
                           legend.labs = c("Inflamed", "Excluded", "Desert"), 
                           conf.int = F,          # Add confidence interval
                           pval = FALSE,              # Add p-value
                           risk.table = TRUE,  title = "PFS for Atezo by manual method", ggtheme=custom_theme(),
                           surv.median.line = "hv")

p_val = survdiff(Surv(PFS_MONTHS, PFS_CENSOR) ~ Final.call, data = A_dat)
p_val = round(pchisq(q = p_val$chisq, df = 2, lower.tail = F), 5)

med_time = surv_median(fit_manual)[,2]

p_manual_A_PFS$plot <- p_manual_A_PFS$plot +
  annotate("text", size = 5, x = 28, y = 0.8, label = paste0("p=", p_val), cex=4, col="black", vjust=0, hjust = 1.1, fontface=1) + 
  annotate("text", size = 5, x = med_time[1], y = 0.6, label = round(med_time[1], 1), cex=4, col="black", vjust=0, hjust = -1, fontface=1) + 
  annotate("text", size = 5, x = med_time[2], y = 0.6, label = round(med_time[2], 1), cex=4, col="black", vjust=0, hjust = 0, fontface=1) + 
  annotate("text", size = 5, x = med_time[3], y = 0.6, label = round(med_time[3], 1), cex=4, col="black", vjust=0, hjust = 1, fontface=1)

print(p_manual_A_PFS)




p_cutoff_A_PFS = ggsurvplot(fit_cutoff, data = A_dat, palette = COLOR, size = 1.5, 
                           font.main = c(16, "bold"), legend.title = "Immunophenotyping",
                           legend.labs = c("Inflamed", "Excluded", "Desert"),
                           conf.int = F,          # Add confidence interval
                           pval = FALSE,              # Add p-value
                           risk.table = TRUE,  title = "PFS for Atezo by cutoff method", ggtheme=custom_theme(),
                           surv.median.line = "hv")

p_val = survdiff(Surv(PFS_MONTHS, PFS_CENSOR) ~ cutoff, data = A_dat)
p_val = round(pchisq(q = p_val$chisq, df = 2, lower.tail = F), 5)

med_time = surv_median(fit_cutoff)[,2]

p_cutoff_A_PFS$plot <- p_cutoff_A_PFS$plot +
  annotate("text", size = 5, x = 28, y = 0.8, label = paste0("p=", p_val), cex=4, col="black", vjust=0, hjust = 1.1, fontface=1) + 
  annotate("text", size = 5, x = med_time[1], y = 0.6, label = round(med_time[1], 1), cex=4, col="black", vjust=0, hjust = 1.5, fontface=1) + 
  annotate("text", size = 5, x = med_time[2], y = 0.6, label = round(med_time[2], 1), cex=4, col="black", vjust=0, hjust = 0, fontface=1) + 
  annotate("text", size = 5, x = med_time[3], y = 0.6, label = round(med_time[3], 1), cex=4, col="black", vjust=0, hjust = -1, fontface=1)

print(p_cutoff_A_PFS)





p_SVM_A_PFS = ggsurvplot(fit_SVM, data = A_dat, palette = COLOR, size = 1.5, 
                        font.main = c(16, "bold"), legend.title = "Immunophenotyping",
                        legend.labs = c("Inflamed", "Excluded", "Desert"),
                        conf.int = F,          # Add confidence interval
                        pval = FALSE,              # Add p-value
                        risk.table = TRUE,  title = "PFS for Atezo by SVM method", ggtheme=custom_theme(),
                        surv.median.line = "hv")

p_val = survdiff(Surv(PFS_MONTHS, PFS_CENSOR) ~ SVM, data = A_dat)
p_val = round(pchisq(q = p_val$chisq, df = 2, lower.tail = F), 5)

med_time = surv_median(fit_spat)[,2]

p_SVM_A_PFS$plot <- p_SVM_A_PFS$plot +
  annotate("text", size = 5, x = 28, y = 0.8, label = paste0("p=", p_val), cex=4, col="black", vjust=0, hjust = 1.1, fontface=1) + 
  annotate("text", size = 5, x = med_time[1], y = 0.6, label = round(med_time[1], 1), cex=4, col="black", vjust=0, hjust = 0, fontface=1) + 
  annotate("text", size = 5, x = med_time[2], y = 0.6, label = round(med_time[2], 1), cex=4, col="black", vjust=0, hjust = -0.2, fontface=1) + 
  annotate("text", size = 5, x = med_time[3], y = 0.6, label = round(med_time[3], 1), cex=4, col="black", vjust=0, hjust = 1.5, fontface=1)

print(p_SVM_A_PFS)





## Doce arm

fit_spat <- survfit(Surv(PFS_MONTHS, PFS_CENSOR) ~ spat, data = D_dat)
fit_manual <- survfit(Surv(PFS_MONTHS, PFS_CENSOR) ~ Final.call, data = D_dat)
fit_cutoff <- survfit(Surv(PFS_MONTHS, PFS_CENSOR) ~ cutoff, data = D_dat)
fit_SVM <- survfit(Surv(PFS_MONTHS, PFS_CENSOR) ~ SVM, data = D_dat)


p_spat_D_PFS = ggsurvplot(fit_spat, data = D_dat, palette = COLOR, size = 1.5, 
                             font.main = c(16, "bold"), legend.title = "Immunophenotyping",
                             legend.labs = c("Inflamed", "Excluded", "Desert"),
                             conf.int = F,          # Add confidence interval
                             pval = FALSE,              # Add p-value
                             risk.table = TRUE,  title = "PFS for Doce by spat method", ggtheme=custom_theme(),
                             surv.median.line = "hv")

p_val = survdiff(Surv(PFS_MONTHS, PFS_CENSOR) ~ spat, data = D_dat)
p_val = round(pchisq(q = p_val$chisq, df = 2, lower.tail = F), 5)

med_time = surv_median(fit_spat)[,2]

p_spat_D_PFS$plot <- p_spat_D_PFS$plot +
  annotate("text", size = 5, x = 28, y = 0.8, label = paste0("p=", p_val), cex=4, col="black", vjust=0, hjust = 1.1, fontface=1) + 
  annotate("text", size = 5, x = med_time[1], y = 0.6, label = round(med_time[1], 1), cex=4, col="black", vjust=0, hjust = -1, fontface=1) + 
  annotate("text", size = 5, x = med_time[2], y = 0.6, label = round(med_time[2], 1), cex=4, col="black", vjust=0, hjust = 0, fontface=1) + 
  annotate("text", size = 5, x = med_time[3], y = 0.6, label = round(med_time[3], 1), cex=4, col="black", vjust=0, hjust = 1, fontface=1)

print(p_spat_D_PFS)




p_manual_D_PFS = ggsurvplot(fit_manual, data = D_dat, palette = COLOR, size = 1.5, 
                           font.main = c(16, "bold"), legend.title = "Immunophenotyping", 
                           legend.labs = c("Inflamed", "Excluded", "Desert"), 
                           conf.int = F,          # Add confidence interval
                           pval = FALSE,              # Add p-value
                           risk.table = TRUE,  title = "PFS for Doce by manual method", ggtheme=custom_theme(),
                           surv.median.line = "hv")

p_val = survdiff(Surv(PFS_MONTHS, PFS_CENSOR) ~ Final.call, data = D_dat)
p_val = round(pchisq(q = p_val$chisq, df = 2, lower.tail = F), 5)

med_time = surv_median(fit_manual)[,2]

p_manual_D_PFS$plot <- p_manual_D_PFS$plot +
  annotate("text", size = 5, x = 28, y = 0.8, label = paste0("p=", p_val), cex=4, col="black", vjust=0, hjust = 1.1, fontface=1) + 
  annotate("text", size = 5, x = med_time[1], y = 0.6, label = round(med_time[1], 1), cex=4, col="black", vjust=0, hjust = -2, fontface=1) + 
  annotate("text", size = 5, x = med_time[2], y = 0.6, label = round(med_time[2], 1), cex=4, col="black", vjust=0, hjust = 0, fontface=1) + 
  annotate("text", size = 5, x = med_time[3], y = 0.6, label = round(med_time[3], 1), cex=4, col="black", vjust=0, hjust = 1, fontface=1)

print(p_manual_D_PFS)



p_cutoff_D_PFS = ggsurvplot(fit_cutoff, data = D_dat, palette = COLOR, size = 1.5, 
                          font.main = c(16, "bold"), legend.title = "Immunophenotyping",
                          legend.labs = c("Inflamed", "Excluded", "Desert"),
                          conf.int = F,          # Add confidence interval
                          pval = FALSE,              # Add p-value
                          risk.table = TRUE,  title = "PFS for Doce by cutoff method", ggtheme=custom_theme(),
                          surv.median.line = "hv")

p_val = survdiff(Surv(PFS_MONTHS, PFS_CENSOR) ~ cutoff, data = D_dat)
p_val = round(pchisq(q = p_val$chisq, df = 2, lower.tail = F), 5)

med_time = surv_median(fit_cutoff)[,2]

p_cutoff_D_PFS$plot <- p_cutoff_D_PFS$plot +
  annotate("text", size = 5, x = 28, y = 0.8, label = paste0("p=", p_val), cex=4, col="black", vjust=0, hjust = 1.1, fontface=1) + 
  annotate("text", size = 5, x = med_time[1], y = 0.6, label = round(med_time[1], 1), cex=4, col="black", vjust=0, hjust = -1, fontface=1) + 
  annotate("text", size = 5, x = med_time[2], y = 0.6, label = round(med_time[2], 1), cex=4, col="black", vjust=0, hjust = 0, fontface=1) + 
  annotate("text", size = 5, x = med_time[3], y = 0.6, label = round(med_time[3], 1), cex=4, col="black", vjust=0, hjust = 1, fontface=1)

print(p_cutoff_D_PFS)




p_SVM_D_PFS = ggsurvplot(fit_SVM, data = D_dat, palette = COLOR, size = 1.5, 
                            font.main = c(16, "bold"), legend.title = "Immunophenotyping", 
                            legend.labs = c("Inflamed", "Excluded", "Desert"), 
                            conf.int = F,          # Add confidence interval
                            pval = FALSE,              # Add p-value
                            risk.table = TRUE,  title = "PFS for Doce by SVM method", ggtheme=custom_theme(),
                            surv.median.line = "hv")

p_val = survdiff(Surv(PFS_MONTHS, PFS_CENSOR) ~ SVM, data = D_dat)
p_val = round(pchisq(q = p_val$chisq, df = 2, lower.tail = F), 5)

med_time = surv_median(fit_SVM)[,2]

p_SVM_D_PFS$plot <- p_SVM_D_PFS$plot +
  annotate("text", size = 5, x = 28, y = 0.8, label = paste0("p=", p_val), cex=4, col="black", vjust=0, hjust = 1.1, fontface=1) + 
  annotate("text", size = 5, x = med_time[1], y = 0.6, label = round(med_time[1], 1), cex=4, col="black", vjust=0, hjust = -2, fontface=1) + 
  annotate("text", size = 5, x = med_time[2], y = 0.6, label = round(med_time[2], 1), cex=4, col="black", vjust=0, hjust = 0, fontface=1) + 
  annotate("text", size = 5, x = med_time[3], y = 0.6, label = round(med_time[3], 1), cex=4, col="black", vjust=0, hjust = 1, fontface=1)

print(p_SVM_D_PFS)




```


```{r}

splots <- list()
splots[[1]] <- p_cutoff_A_OS
splots[[2]] <- p_SVM_A_OS
splots[[3]] <- p_spat_A_OS
splots[[4]] <- p_manual_A_OS
splots[[5]] <- p_cutoff_D_OS
splots[[6]] <- p_SVM_D_OS
splots[[7]] <- p_spat_D_OS
splots[[8]] <- p_manual_D_OS



splots[[9]] <- p_cutoff_A_PFS
splots[[10]] <- p_SVM_A_PFS
splots[[11]] <- p_spat_A_PFS
splots[[12]] <- p_manual_A_PFS
splots[[13]] <- p_cutoff_D_PFS
splots[[14]] <- p_SVM_D_PFS
splots[[15]] <- p_spat_D_PFS
splots[[16]] <- p_manual_D_PFS



png("OS_comp_new_preferred_OAK_pip1-3.png", width = 6000, height = 4125, res = 300)
# Arrange multiple ggsurvplots and print the output
arrange_ggsurvplots(list(splots[[1]], splots[[5]], splots[[2]], splots[[6]],
                         splots[[3]], splots[[7]], splots[[4]], splots[[8]]), 
                    print = TRUE, ncol = 4, nrow = 2, risk.table.height = 0.2)
dev.off()


png("PFS_comp_new_preferred_OAK_pip1-3.png", width = 6000, height = 4125, res = 300)
# Arrange multiple ggsurvplots and print the output
arrange_ggsurvplots(list(splots[[9]], splots[[13]], splots[[10]], splots[[14]],
                         splots[[11]], splots[[15]], splots[[12]], splots[[16]]), 
                    print = TRUE, ncol = 4, nrow = 2, risk.table.height = 0.2)
dev.off()


```





# prediction on IMPassion130 (combing arms)
```{r, warning=FALSE}
Jeff_IMP130 = readxl::read_xlsx('20221002_IMP130_tracker.xlsx', sheet = 1, col_types = c(rep("text", 12), rep("numeric", 27))) %>% mutate(Final.call = factor(Immunophenotype_HK, levels = c("Inflamed", "Excluded", "Desert")))
Jeff_IMP130 = Jeff_IMP130[-c(1:8, 10, 11, 14, 16, 17), ]
Jeff_IMP130$ID = paste0(Jeff_IMP130$Block, '_', as.numeric(Jeff_IMP130$`Patient Number`), '_ckpos_tiles.csv')
Jeff_IMP130 = Jeff_IMP130[, c(21:29, 31:39, 40, 41)]; names(Jeff_IMP130)[1:18] = gsub(" ", ".", names(Jeff_IMP130)[1:18])

Xiao_IMP130 = read.csv('IMPassion130_res.csv'); Xiao_IMP130 = Xiao_IMP130[, -which(colnames(Xiao_IMP130) == "ID.1")[1]]

# Jeff_IMP130$ID[!(Jeff_IMP130$ID %in% Xiao_IMP130$ID)] 
# "HP-208267_1175_ckpos_tiles.csv" "HP-208290_1209_ckpos_tiles.csv" "HP-208637_1517_ckpos_tiles.csv" 
# these 3 files are either short of pos tiles or neg tiles

combine_IMP130 = merge(Jeff_IMP130, Xiao_IMP130, by = "ID")
combine_IMP130 = combine_IMP130[complete.cases(combine_IMP130),]

pred <- predict(rf_training, 
                combine_IMP130[, fea], 
                type = "prob")

xtab = table(factor(c("Desert", "Excluded", "Inflamed")[apply(pred, 1, which.max)], levels = c("Inflamed", "Excluded", "Desert"))
, combine_IMP130$Final.call)

print(paste0("Classification accuracy is ", sum(diag(xtab))/sum(xtab)))

vcd::Kappa(xtab)
xtab
```


```{r}

tmp1 = read.csv('20221130_IMP130_tracker_ANON.csv') %>% select(uni_id = hashed.uniId, HK_block = 'Specimen.._HK', 
                                                               SVM = SVM_prediction, cutoff = Slide_Cutoff_prediction)
tmp2 = read.csv('wo29522_clin_jea_hk_10022022.csv')

tmp3 = merge(tmp1, tmp2, by = "uni_id")

combine_IMP130 = combine_IMP130 %>% mutate(HK_block = substr(ID, 1, 9),
                                     spat = factor(c("Desert", "Excluded", "Inflamed")[apply(pred, 1, which.max)], levels = c("Inflamed", "Excluded", "Desert"))) %>% select(HK_block, Final.call, spat)

dat_IMP130 = merge(combine_IMP130, 
                   tmp3 %>% select(HK_block, SVM, cutoff, os_months, os_cnsr, pfs_months, pfs_cnsr, arm), 
                   by = "HK_block")

dat_IMP130$SVM = factor(dat_IMP130$SVM, levels = c("Inflamed", "Excluded", "Desert"))
dat_IMP130$cutoff = factor(dat_IMP130$cutoff, levels = c("Inflamed", "Excluded", "Desert"))
```



# OS Survival analysis (IMPassion130)
```{r}
COLOR <- c("#ED7D31", "#4472C4", "#A5A5A5")

A_dat = dat_IMP130 %>% filter(arm == "MPDL3280A")

D_dat = dat_IMP130 %>% filter(arm == "PLACEBO")
#######################################################################################################
########################            OS for spat and manual methods         ########################
#######################################################################################################

## Atezo arm
fit_spat <- survfit(Surv(os_months, 1-os_cnsr) ~ spat, data = A_dat)
fit_manual <- survfit(Surv(os_months, 1-os_cnsr) ~ Final.call, data = A_dat)
fit_cutoff <- survfit(Surv(os_months, 1-os_cnsr) ~ cutoff, data = A_dat)
fit_SVM <- survfit(Surv(os_months, 1-os_cnsr) ~ SVM, data = A_dat)


p_spat_A_OS = ggsurvplot(fit_spat, data = A_dat, palette = COLOR, size = 1.5, 
                font.main = c(16, "bold"), legend.title = "Immunophenotyping",
                legend.labs = c("Inflamed", "Excluded", "Desert"),
                conf.int = F,          # Add confidence interval
                pval = FALSE,              # Add p-value
                risk.table = TRUE,  title = "OS for Atezo by spat method", ggtheme=custom_theme(),
                surv.median.line = "hv")

p_val = survdiff(Surv(os_months, 1-os_cnsr) ~ spat, data = A_dat)
p_val = round(pchisq(q = p_val$chisq, df = 2, lower.tail = F), 5)

med_time = surv_median(fit_spat)[,2]

p_spat_A_OS$plot <- p_spat_A_OS$plot +
  annotate("text", size = 5, x = 28, y = 0.8, label = paste0("p=", p_val), cex=4, col="black", vjust=0, hjust = 1.1, fontface=1) + 
  annotate("text", size = 5, x = med_time[1], y = 0.6, label = round(med_time[1], 1), cex=4, col="black", vjust=0, hjust = -1, fontface=1) + 
  annotate("text", size = 5, x = med_time[2], y = 0.6, label = round(med_time[2], 1), cex=4, col="black", vjust=0, hjust = 0, fontface=1) + 
  annotate("text", size = 5, x = med_time[3], y = 0.6, label = round(med_time[3], 1), cex=4, col="black", vjust=0, hjust = 1, fontface=1)

print(p_spat_A_OS)



p_manual_A_OS = ggsurvplot(fit_manual, data = A_dat, palette = COLOR, size = 1.5, 
                font.main = c(16, "bold"), legend.title = "Immunophenotyping", 
                legend.labs = c("Inflamed", "Excluded", "Desert"), 
                conf.int = F,          # Add confidence interval
                pval = FALSE,              # Add p-value
                risk.table = TRUE,  title = "OS for Atezo by manual method", ggtheme=custom_theme(),
                surv.median.line = "hv")

p_val = survdiff(Surv(os_months, 1-os_cnsr) ~ Final.call, data = A_dat)
p_val = round(pchisq(q = p_val$chisq, df = 2, lower.tail = F), 5)

med_time = surv_median(fit_manual)[,2]

p_manual_A_OS$plot <- p_manual_A_OS$plot +
  annotate("text", size = 5, x = 28, y = 0.8, label = paste0("p=", p_val), cex=4, col="black", vjust=0, hjust = 1.1, fontface=1) + 
  annotate("text", size = 5, x = med_time[1], y = 0.6, label = round(med_time[1], 1), cex=4, col="black", vjust=0, hjust = -1.5, fontface=1) + 
  annotate("text", size = 5, x = med_time[2], y = 0.6, label = round(med_time[2], 1), cex=4, col="black", vjust=0, hjust = 0, fontface=1) + 
  annotate("text", size = 5, x = med_time[3], y = 0.6, label = round(med_time[3], 1), cex=4, col="black", vjust=0, hjust = 1, fontface=1)

print(p_manual_A_OS)


p_cutoff_A_OS = ggsurvplot(fit_cutoff, data = A_dat, palette = COLOR, size = 1.5, 
                         font.main = c(16, "bold"), legend.title = "Immunophenotyping",
                         legend.labs = c("Inflamed", "Excluded", "Desert"),
                         conf.int = F,          # Add confidence interval
                         pval = FALSE,              # Add p-value
                         risk.table = TRUE,  title = "OS for Atezo by cutoff method", ggtheme=custom_theme(),
                         surv.median.line = "hv")

p_val = survdiff(Surv(os_months, 1-os_cnsr) ~ cutoff, data = A_dat)
p_val = round(pchisq(q = p_val$chisq, df = 2, lower.tail = F), 5)

med_time = surv_median(fit_cutoff)[,2]

p_cutoff_A_OS$plot <- p_cutoff_A_OS$plot +
  annotate("text", size = 5, x = 28, y = 0.8, label = paste0("p=", p_val), cex=4, col="black", vjust=0, hjust = 1.1, fontface=1) + 
  annotate("text", size = 5, x = med_time[1], y = 0.6, label = round(med_time[1], 1), cex=4, col="black", vjust=0, hjust = -1, fontface=1) + 
  annotate("text", size = 5, x = med_time[2], y = 0.6, label = round(med_time[2], 1), cex=4, col="black", vjust=0, hjust = 0, fontface=1) + 
  annotate("text", size = 5, x = med_time[3], y = 0.6, label = round(med_time[3], 1), cex=4, col="black", vjust=0, hjust = 1, fontface=1)

print(p_cutoff_A_OS)



p_SVM_A_OS = ggsurvplot(fit_SVM, data = A_dat, palette = COLOR, size = 1.5, 
                         font.main = c(16, "bold"), legend.title = "Immunophenotyping",
                         legend.labs = c("Inflamed", "Excluded", "Desert"),
                         conf.int = F,          # Add confidence interval
                         pval = FALSE,              # Add p-value
                         risk.table = TRUE,  title = "OS for Atezo by SVM method", ggtheme=custom_theme(),
                         surv.median.line = "hv")

p_val = survdiff(Surv(os_months, 1-os_cnsr) ~ SVM, data = A_dat)
p_val = round(pchisq(q = p_val$chisq, df = 2, lower.tail = F), 5)

med_time = surv_median(fit_SVM)[,2]

p_SVM_A_OS$plot <- p_SVM_A_OS$plot +
  annotate("text", size = 5, x = 28, y = 0.8, label = paste0("p=", p_val), cex=4, col="black", vjust=0, hjust = 1.1, fontface=1) + 
  annotate("text", size = 5, x = med_time[1], y = 0.6, label = round(med_time[1], 1), cex=4, col="black", vjust=0, hjust = -1, fontface=1) + 
  annotate("text", size = 5, x = med_time[2], y = 0.6, label = round(med_time[2], 1), cex=4, col="black", vjust=0, hjust = 0, fontface=1) + 
  annotate("text", size = 5, x = med_time[3], y = 0.6, label = round(med_time[3], 1), cex=4, col="black", vjust=0, hjust = 1, fontface=1)

print(p_SVM_A_OS)




## Placebo arm
fit_spat <- survfit(Surv(os_months, 1-os_cnsr) ~ spat, data = D_dat)
fit_manual <- survfit(Surv(os_months, 1-os_cnsr) ~ Final.call, data = D_dat)
fit_cutoff <- survfit(Surv(os_months, 1-os_cnsr) ~ cutoff, data = D_dat)
fit_SVM <- survfit(Surv(os_months, 1-os_cnsr) ~ SVM, data = D_dat)


p_spat_D_OS = ggsurvplot(fit_spat, data = D_dat, palette = COLOR, size = 1.5, 
                font.main = c(16, "bold"), legend.title = "Immunophenotyping",
                legend.labs = c("Inflamed", "Excluded", "Desert"),
                conf.int = F,          # Add confidence interval
                pval = FALSE,              # Add p-value
                risk.table = TRUE,  title = "OS for Placebo by spat method", ggtheme=custom_theme(),
                surv.median.line = "hv")

p_val = survdiff(Surv(os_months, 1-os_cnsr) ~ spat, data = D_dat)
p_val = round(pchisq(q = p_val$chisq, df = 2, lower.tail = F), 5)

med_time = surv_median(fit_spat)[,2]

p_spat_D_OS$plot <- p_spat_D_OS$plot +
  annotate("text", size = 5, x = 28, y = 0.8, label = paste0("p=", p_val), cex=4, col="black", vjust=0, hjust = 1.1, fontface=1) + 
  annotate("text", size = 5, x = med_time[1], y = 0.6, label = round(med_time[1], 1), cex=4, col="black", vjust=0, hjust = 2, fontface=1) + 
  annotate("text", size = 5, x = med_time[2], y = 0.6, label = round(med_time[2], 1), cex=4, col="black", vjust=0, hjust = -1.5, fontface=1) + 
  annotate("text", size = 5, x = med_time[3], y = 0.6, label = round(med_time[3], 1), cex=4, col="black", vjust=0, hjust = 0.5, fontface=1)

print(p_spat_D_OS)



p_manual_D_OS = ggsurvplot(fit_manual, data = D_dat, palette = COLOR, size = 1.5, 
                font.main = c(16, "bold"), legend.title = "Immunophenotyping", 
                legend.labs = c("Inflamed", "Excluded", "Desert"), 
                conf.int = F,          # Add confidence interval
                pval = FALSE,              # Add p-value
                risk.table = TRUE,  title = "OS for Placebo by manual method", ggtheme=custom_theme(),
                surv.median.line = "hv")

p_val = survdiff(Surv(os_months, 1-os_cnsr) ~ Final.call, data = D_dat)
p_val = round(pchisq(q = p_val$chisq, df = 2, lower.tail = F), 5)

med_time = surv_median(fit_manual)[,2]

p_manual_D_OS$plot <- p_manual_D_OS$plot +
  annotate("text", size = 5, x = 28, y = 0.8, label = paste0("p=", p_val), cex=4, col="black", vjust=0, hjust = 1.1, fontface=1) + 
  annotate("text", size = 5, x = med_time[1], y = 0.6, label = round(med_time[1], 1), cex=4, col="black", vjust=0, hjust = 2, fontface=1) + 
  annotate("text", size = 5, x = med_time[2], y = 0.6, label = round(med_time[2], 1), cex=4, col="black", vjust=0, hjust = 0, fontface=1) + 
  annotate("text", size = 5, x = med_time[3], y = 0.6, label = round(med_time[3], 1), cex=4, col="black", vjust=0, hjust = -2, fontface=1)

print(p_manual_D_OS)



p_cutoff_D_OS = ggsurvplot(fit_cutoff, data = D_dat, palette = COLOR, size = 1.5, 
                         font.main = c(16, "bold"), legend.title = "Immunophenotyping",
                         legend.labs = c("Inflamed", "Excluded", "Desert"),
                         conf.int = F,          # Add confidence interval
                         pval = FALSE,              # Add p-value
                         risk.table = TRUE,  title = "OS for Placebo by cutoff method", ggtheme=custom_theme(),
                         surv.median.line = "hv")

p_val = survdiff(Surv(os_months, 1-os_cnsr) ~ cutoff, data = D_dat)
p_val = round(pchisq(q = p_val$chisq, df = 2, lower.tail = F), 5)

med_time = surv_median(fit_cutoff)[,2]

p_cutoff_D_OS$plot <- p_cutoff_D_OS$plot +
  annotate("text", size = 5, x = 28, y = 0.8, label = paste0("p=", p_val), cex=4, col="black", vjust=0, hjust = 1.1, fontface=1) + 
  annotate("text", size = 5, x = med_time[1], y = 0.6, label = round(med_time[1], 1), cex=4, col="black", vjust=0, hjust = -1, fontface=1) + 
  annotate("text", size = 5, x = med_time[2], y = 0.6, label = round(med_time[2], 1), cex=4, col="black", vjust=0, hjust = 0, fontface=1) + 
  annotate("text", size = 5, x = med_time[3], y = 0.6, label = round(med_time[3], 1), cex=4, col="black", vjust=0, hjust = 1, fontface=1)

print(p_cutoff_D_OS)



p_SVM_D_OS = ggsurvplot(fit_SVM, data = D_dat, palette = COLOR, size = 1.5, 
                         font.main = c(16, "bold"), legend.title = "Immunophenotyping",
                         legend.labs = c("Inflamed", "Excluded", "Desert"),
                         conf.int = F,          # Add confidence interval
                         pval = FALSE,              # Add p-value
                         risk.table = TRUE,  title = "OS for Placebo by SVM method", ggtheme=custom_theme(),
                         surv.median.line = "hv")

p_val = survdiff(Surv(os_months, 1-os_cnsr) ~ SVM, data = D_dat)
p_val = round(pchisq(q = p_val$chisq, df = 2, lower.tail = F), 5)

med_time = surv_median(fit_SVM)[,2]

p_SVM_D_OS$plot <- p_SVM_D_OS$plot +
  annotate("text", size = 5, x = 28, y = 0.8, label = paste0("p=", p_val), cex=4, col="black", vjust=0, hjust = 1.1, fontface=1) + 
  annotate("text", size = 5, x = med_time[1], y = 0.6, label = round(med_time[1], 1), cex=4, col="black", vjust=0, hjust = -1, fontface=1) + 
  annotate("text", size = 5, x = med_time[2], y = 0.6, label = round(med_time[2], 1), cex=4, col="black", vjust=0, hjust = 0, fontface=1) + 
  annotate("text", size = 5, x = med_time[3], y = 0.6, label = round(med_time[3], 1), cex=4, col="black", vjust=0, hjust = 1, fontface=1)

print(p_SVM_D_OS)


```



# PFS Survival analysis (IMPassion130)
```{r}

#######################################################################################################
########################            PFS for spat and manual methods         ########################
#######################################################################################################

## Atezo arm
fit_spat <- survfit(Surv(pfs_months, 1-pfs_cnsr) ~ spat, data = A_dat)
fit_manual <- survfit(Surv(pfs_months, 1-pfs_cnsr) ~ Final.call, data = A_dat)
fit_cutoff <- survfit(Surv(pfs_months, 1-pfs_cnsr) ~ cutoff, data = A_dat)
fit_SVM <- survfit(Surv(pfs_months, 1-pfs_cnsr) ~ SVM, data = A_dat)


p_spat_A_pfs = ggsurvplot(fit_spat, data = A_dat, palette = COLOR, size = 1.5, 
                          font.main = c(16, "bold"), legend.title = "Immunophenotyping",
                          legend.labs = c("Inflamed", "Excluded", "Desert"),
                          conf.int = F,          # Add confidence interval
                          pval = FALSE,              # Add p-value
                          risk.table = TRUE,  title = "PFS for Atezo by spat method", ggtheme=custom_theme(),
                          surv.median.line = "hv")

p_val = survdiff(Surv(pfs_months, 1-pfs_cnsr) ~ spat, data = A_dat)
p_val = round(pchisq(q = p_val$chisq, df = 2, lower.tail = F), 5)

med_time = surv_median(fit_spat)[,2]

p_spat_A_pfs$plot <- p_spat_A_pfs$plot +
  annotate("text", size = 5, x = 28, y = 0.8, label = paste0("p=", p_val), cex=4, col="black", vjust=0, hjust = 1.1, fontface=1) + 
  annotate("text", size = 5, x = med_time[1], y = 0.6, label = round(med_time[1], 1), cex=4, col="black", vjust=0, hjust = -1.5, fontface=1) + 
  annotate("text", size = 5, x = med_time[2], y = 0.6, label = round(med_time[2], 1), cex=4, col="black", vjust=0, hjust = 0, fontface=1) + 
  annotate("text", size = 5, x = med_time[3], y = 0.6, label = round(med_time[3], 1), cex=4, col="black", vjust=0, hjust = 1.5, fontface=1)

print(p_spat_A_pfs)



p_manual_A_pfs = ggsurvplot(fit_manual, data = A_dat, palette = COLOR, size = 1.5, 
                           font.main = c(16, "bold"), legend.title = "Immunophenotyping", 
                           legend.labs = c("Inflamed", "Excluded", "Desert"), 
                           conf.int = F,          # Add confidence interval
                           pval = FALSE,              # Add p-value
                           risk.table = TRUE,  title = "PFS for Atezo by manual method", ggtheme=custom_theme(),
                           surv.median.line = "hv")

p_val = survdiff(Surv(pfs_months, 1-pfs_cnsr) ~ Final.call, data = A_dat)
p_val = round(pchisq(q = p_val$chisq, df = 2, lower.tail = F), 5)

med_time = surv_median(fit_manual)[,2]

p_manual_A_pfs$plot <- p_manual_A_pfs$plot +
  annotate("text", size = 5, x = 28, y = 0.8, label = paste0("p=", p_val), cex=4, col="black", vjust=0, hjust = 1.1, fontface=1) + 
  annotate("text", size = 5, x = med_time[1], y = 0.6, label = round(med_time[1], 1), cex=4, col="black", vjust=0, hjust = -1.2, fontface=1) + 
  annotate("text", size = 5, x = med_time[2], y = 0.6, label = round(med_time[2], 1), cex=4, col="black", vjust=0, hjust = 0.5, fontface=1) + 
  annotate("text", size = 5, x = med_time[3], y = 0.6, label = round(med_time[3], 1), cex=4, col="black", vjust=0, hjust = 1.5, fontface=1)

print(p_manual_A_pfs)


p_cutoff_A_pfs = ggsurvplot(fit_cutoff, data = A_dat, palette = COLOR, size = 1.5, 
                         font.main = c(16, "bold"), legend.title = "Immunophenotyping",
                         legend.labs = c("Inflamed", "Excluded", "Desert"),
                         conf.int = F,          # Add confidence interval
                         pval = FALSE,              # Add p-value
                         risk.table = TRUE,  title = "PFS for Placebo by cutoff method", ggtheme=custom_theme(),
                         surv.median.line = "hv")

p_val = survdiff(Surv(pfs_months, 1-pfs_cnsr) ~ cutoff, data = A_dat)
p_val = round(pchisq(q = p_val$chisq, df = 2, lower.tail = F), 5)

med_time = surv_median(fit_cutoff)[,2]

p_cutoff_A_pfs$plot <- p_cutoff_A_pfs$plot +
  annotate("text", size = 5, x = 28, y = 0.8, label = paste0("p=", p_val), cex=4, col="black", vjust=0, hjust = 1.1, fontface=1) + 
  annotate("text", size = 5, x = med_time[1], y = 0.6, label = round(med_time[1], 1), cex=4, col="black", vjust=0, hjust = -1, fontface=1) + 
  annotate("text", size = 5, x = med_time[2], y = 0.6, label = round(med_time[2], 1), cex=4, col="black", vjust=0, hjust = 0, fontface=1) + 
  annotate("text", size = 5, x = med_time[3], y = 0.6, label = round(med_time[3], 1), cex=4, col="black", vjust=0, hjust = 1, fontface=1)

print(p_cutoff_A_pfs)



p_SVM_A_pfs = ggsurvplot(fit_SVM, data = A_dat, palette = COLOR, size = 1.5, 
                         font.main = c(16, "bold"), legend.title = "Immunophenotyping",
                         legend.labs = c("Inflamed", "Excluded", "Desert"),
                         conf.int = F,          # Add confidence interval
                         pval = FALSE,              # Add p-value
                         risk.table = TRUE,  title = "PFS for Placebo by SVM method", ggtheme=custom_theme(),
                         surv.median.line = "hv")

p_val = survdiff(Surv(pfs_months, 1-pfs_cnsr) ~ SVM, data = A_dat)
p_val = round(pchisq(q = p_val$chisq, df = 2, lower.tail = F), 5)

med_time = surv_median(fit_SVM)[,2]

p_SVM_A_pfs$plot <- p_SVM_A_pfs$plot +
  annotate("text", size = 5, x = 28, y = 0.8, label = paste0("p=", p_val), cex=4, col="black", vjust=0, hjust = 1.1, fontface=1) + 
  annotate("text", size = 5, x = med_time[1], y = 0.6, label = round(med_time[1], 1), cex=4, col="black", vjust=0, hjust = -1, fontface=1) + 
  annotate("text", size = 5, x = med_time[2], y = 0.6, label = round(med_time[2], 1), cex=4, col="black", vjust=0, hjust = 0, fontface=1) + 
  annotate("text", size = 5, x = med_time[3], y = 0.6, label = round(med_time[3], 1), cex=4, col="black", vjust=0, hjust = 1, fontface=1)

print(p_SVM_A_pfs)






## Placebo arm
fit_spat <- survfit(Surv(pfs_months, 1-pfs_cnsr) ~ spat, data = D_dat)
fit_manual <- survfit(Surv(pfs_months, 1-pfs_cnsr) ~ Final.call, data = D_dat)
fit_cutoff <- survfit(Surv(pfs_months, 1-pfs_cnsr) ~ cutoff, data = D_dat)
fit_SVM <- survfit(Surv(pfs_months, 1-pfs_cnsr) ~ SVM, data = D_dat)




p_spat_D_pfs = ggsurvplot(fit_spat, data = D_dat, palette = COLOR, size = 1.5, 
                         font.main = c(16, "bold"), legend.title = "Immunophenotyping",
                         legend.labs = c("Inflamed", "Excluded", "Desert"),
                         conf.int = F,          # Add confidence interval
                         pval = FALSE,              # Add p-value
                         risk.table = TRUE,  title = "PFS for Placebo by spat method", ggtheme=custom_theme(),
                         surv.median.line = "hv")

p_val = survdiff(Surv(pfs_months, 1-pfs_cnsr) ~ spat, data = D_dat)
p_val = round(pchisq(q = p_val$chisq, df = 2, lower.tail = F), 5)

med_time = surv_median(fit_spat)[,2]

p_spat_D_pfs$plot <- p_spat_D_pfs$plot +
  annotate("text", size = 5, x = 28, y = 0.8, label = paste0("p=", p_val), cex=4, col="black", vjust=0, hjust = 1.1, fontface=1) + 
  annotate("text", size = 5, x = med_time[1], y = 0.6, label = round(med_time[1], 1), cex=4, col="black", vjust=0, hjust = 1.5, fontface=1) + 
  annotate("text", size = 5, x = med_time[2], y = 0.6, label = round(med_time[2], 1), cex=4, col="black", vjust=0, hjust = -1.5, fontface=1) + 
  annotate("text", size = 5, x = med_time[3], y = 0.6, label = round(med_time[3], 1), cex=4, col="black", vjust=0, hjust = 0, fontface=1)

print(p_spat_D_pfs)



p_manual_D_pfs = ggsurvplot(fit_manual, data = D_dat, palette = COLOR, size = 1.5, 
                           font.main = c(16, "bold"), legend.title = "Immunophenotyping", 
                           legend.labs = c("Inflamed", "Excluded", "Desert"), 
                           conf.int = F,          # Add confidence interval
                           pval = FALSE,              # Add p-value
                           risk.table = TRUE,  title = "PFS for Placebo by manual method", ggtheme=custom_theme(),
                           surv.median.line = "hv")

p_val = survdiff(Surv(pfs_months, 1-pfs_cnsr) ~ Final.call, data = D_dat)
p_val = round(pchisq(q = p_val$chisq, df = 2, lower.tail = F), 5)

med_time = surv_median(fit_manual)[,2]

p_manual_D_pfs$plot <- p_manual_D_pfs$plot +
  annotate("text", size = 5, x = 28, y = 0.8, label = paste0("p=", p_val), cex=4, col="black", vjust=0, hjust = 1.1, fontface=1) + 
  annotate("text", size = 5, x = med_time[1], y = 0.6, label = round(med_time[1], 1), cex=4, col="black", vjust=0, hjust = 1.6, fontface=1) + 
  annotate("text", size = 5, x = med_time[2], y = 0.6, label = round(med_time[2], 1), cex=4, col="black", vjust=0, hjust = 0.6, fontface=1) + 
  annotate("text", size = 5, x = med_time[3], y = 0.6, label = round(med_time[3], 1), cex=4, col="black", vjust=0, hjust = -1.6, fontface=1)

print(p_manual_D_pfs)


p_cutoff_D_pfs = ggsurvplot(fit_cutoff, data = D_dat, palette = COLOR, size = 1.5, 
                         font.main = c(16, "bold"), legend.title = "Immunophenotyping",
                         legend.labs = c("Inflamed", "Excluded", "Desert"),
                         conf.int = F,          # Add confidence interval
                         pval = FALSE,              # Add p-value
                         risk.table = TRUE,  title = "PFS for Placebo by cutoff method", ggtheme=custom_theme(),
                         surv.median.line = "hv")

p_val = survdiff(Surv(pfs_months, 1-pfs_cnsr) ~ cutoff, data = D_dat)
p_val = round(pchisq(q = p_val$chisq, df = 2, lower.tail = F), 5)

med_time = surv_median(fit_cutoff)[,2]

p_cutoff_D_pfs$plot <- p_cutoff_D_pfs$plot +
  annotate("text", size = 5, x = 28, y = 0.8, label = paste0("p=", p_val), cex=4, col="black", vjust=0, hjust = 1.1, fontface=1) + 
  annotate("text", size = 5, x = med_time[1], y = 0.6, label = round(med_time[1], 1), cex=4, col="black", vjust=0, hjust = -1, fontface=1) + 
  annotate("text", size = 5, x = med_time[2], y = 0.6, label = round(med_time[2], 1), cex=4, col="black", vjust=0, hjust = 0, fontface=1) + 
  annotate("text", size = 5, x = med_time[3], y = 0.6, label = round(med_time[3], 1), cex=4, col="black", vjust=0, hjust = 1, fontface=1)

print(p_cutoff_D_pfs)



p_SVM_D_pfs = ggsurvplot(fit_SVM, data = D_dat, palette = COLOR, size = 1.5, 
                         font.main = c(16, "bold"), legend.title = "Immunophenotyping",
                         legend.labs = c("Inflamed", "Excluded", "Desert"),
                         conf.int = F,          # Add confidence interval
                         pval = FALSE,              # Add p-value
                         risk.table = TRUE,  title = "PFS for Placebo by SVM method", ggtheme=custom_theme(),
                         surv.median.line = "hv")

p_val = survdiff(Surv(pfs_months, 1-pfs_cnsr) ~ SVM, data = D_dat)
p_val = round(pchisq(q = p_val$chisq, df = 2, lower.tail = F), 5)

med_time = surv_median(fit_SVM)[,2]

p_SVM_D_pfs$plot <- p_SVM_D_pfs$plot +
  annotate("text", size = 5, x = 28, y = 0.8, label = paste0("p=", p_val), cex=4, col="black", vjust=0, hjust = 1.1, fontface=1) + 
  annotate("text", size = 5, x = med_time[1], y = 0.6, label = round(med_time[1], 1), cex=4, col="black", vjust=0, hjust = -1, fontface=1) + 
  annotate("text", size = 5, x = med_time[2], y = 0.6, label = round(med_time[2], 1), cex=4, col="black", vjust=0, hjust = 0, fontface=1) + 
  annotate("text", size = 5, x = med_time[3], y = 0.6, label = round(med_time[3], 1), cex=4, col="black", vjust=0, hjust = 1, fontface=1)

print(p_SVM_D_pfs)


```





```{r}

splots <- list()
splots[[1]] <- p_cutoff_A_OS
splots[[2]] <- p_SVM_A_OS
splots[[3]] <- p_spat_A_OS
splots[[4]] <- p_manual_A_OS
splots[[5]] <- p_cutoff_D_OS
splots[[6]] <- p_SVM_D_OS
splots[[7]] <- p_spat_D_OS
splots[[8]] <- p_manual_D_OS



splots[[9]] <- p_cutoff_A_pfs
splots[[10]] <- p_SVM_A_pfs
splots[[11]] <- p_spat_A_pfs
splots[[12]] <- p_manual_A_pfs
splots[[13]] <- p_cutoff_D_pfs
splots[[14]] <- p_SVM_D_pfs
splots[[15]] <- p_spat_D_pfs
splots[[16]] <- p_manual_D_pfs



png("OS_comp_new_preferred_IMP130_pip1-3.png", width = 6000, height = 4125, res = 300)
# Arrange multiple ggsurvplots and print the output
arrange_ggsurvplots(list(splots[[1]], splots[[5]], splots[[2]], splots[[6]],
                         splots[[3]], splots[[7]], splots[[4]], splots[[8]]), 
                    print = TRUE, ncol = 4, nrow = 2, risk.table.height = 0.2)
dev.off()


png("PFS_comp_new_preferred_IMP130_pip1-3.png", width = 6000, height = 4125, res = 300)
# Arrange multiple ggsurvplots and print the output
arrange_ggsurvplots(list(splots[[9]], splots[[13]], splots[[10]], splots[[14]],
                         splots[[11]], splots[[15]], splots[[12]], splots[[16]]), 
                    print = TRUE, ncol = 4, nrow = 2, risk.table.height = 0.2)
dev.off()


```
